# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: '**'
  push:
    branches: 'master'

jobs:
  build_dev:
    if: github.ref != 'refs/heads/master'
    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_D }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - name: Install
      run: npm ci

    - name: Test
      run: npm test

    - name: Build
      run: npm run build-dev --if-present
      
  build_master:
    if: github.ref == 'refs/heads/master'
    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_M }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - name: Install
      run: npm ci

    - name: Test
      run: npm test

    - name: Build
      run: npm run build --if-present
